-- 코드를 작성해주세요
SELECT ID, (CASE 
                WHEN GRADE = 4 THEN 'LOW'
                WHEN GRADE = 3 THEN 'MEDIUM'
                WHEN GRADE = 2 THEN 'HIGH'
                WHEN GRADE = 1 THEN 'CRITICAL'
           END)AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GRADE
    FROM ECOLI_DATA
) ECOLI_SIZE
ORDER BY ID;