WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, C.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN CTE C
        ON E.PARENT_ID = C.ID
)
SELECT COUNT(*), GENERATION
FROM CTE C
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = C.ID
)
GROUP BY GENERATION
ORDER BY GENERATION;
